name: Deploy Hello World App

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python (for Python app) or Node.js (for Node.js app)
      uses: actions/setup-python@v2 # For Python
      with:
        python-version: 3.x
      
        node-version: 14

    - name: Install dependencies
      run: |
        pip install --upgrade pip
        pip install -r requirements.txt # For Python
        npm install # For Node.js

    - name: Run the App
      run: |
        python app.py # For Python
        node app.js # For Node.js
